version: '3.7'
services:
  mysqldb:
    image: mysql:8.0.1
    restart: always
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=mySqlDataBase
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass